FROM python:3.9.16

WORKDIR /process

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

COPY process.py .

CMD [ "python", "process.py" ]